### ISSUE TITLE
Incomplete *unpair* when using round-robin store status callback

### ISSUE THREAD

**Issue by jspngh** [espressif/esp-nimble#39]
In the `bleprph` example, the following configuration is used `ble_hs_cfg.store_status_cb = ble_store_util_status_rr;`.
However, this implementation does not work for `BT_NIMBLE_MAX_BONDS` >= 2.
In case of `BLE_STORE_EVENT_OVERFLOW`, `ble_gap_unpair_oldest_peer` does not seem to delete all necessary data.
When I replace it with `ble_store_util_delete_oldest_peer`, it works better.
I am not sure if this because of the changes in `esp-nimble` or if this is also the case in upstream `mynewt-nimble`.

Since we can set the `store_status_cb` to whichever function we want, this is not a giant problem,
but it might be a good idea to update the example to something that works with `esp-nimble`.

**Comment by darshan7patel** [comment]
Hi, this issue was addressed and fixed in this commit:
1.5.0 - [fix(nimble): Fixed ble_gap_unpair_oldest_peer to prevent writing to invalid memory](https://github.com/espressif/esp-nimble/commit/721ef988bffc5525f4797e3d5f237391530d4375)
1.4.0 -[fix(nimble): Fixed ble_gap_unpair_oldest_peer to prevent writing to invalid memory](https://github.com/espressif/esp-nimble/commit/a26c3f9fe9bb74b53003fb572c1e6f3a097a54da)
1.3.0 - [fix(nimble): Fixed incorrect handling of bonded devices](https://github.com/espressif/esp-nimble/commit/ad5695c419d2f2bd9fb014bd4fba61a0c808d346)
