### ISSUE TITLE
implicit declaration of function 'ble_store_config_init'

### ISSUE THREAD

**Issue by Hairy-Lee** [espressif/esp-nimble#56]
ble_store_config_init isn't declared within ..\esp-idf-v4.4.4\components\bt\host\nimble\nimble\nimble\host\store\config\include\store\config\ble_store_config.h

Not obvious if this is intentional or not.

**Comment by rahult-github** [comment]
Hi @Hairy-Lee  , 

 This code is taken as is from upstream nimble. It is not defined in the header file in upstream code either, hence the same replication even in ESP-IDF. 
 
 And in order to access it from examples in IDF, we do forward declaration of same . An instance of it can be seen [here](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/nimble/bleprph/main/main.c#L48).

**Comment by Hairy-Lee** [comment]
Hey @rahult-github 

Thanks for the quick response. I wasn't sure as some init functions are declared in their corresponding header file ble_svc_gap_init() in ble_svc_gap.h for example.
